server:
  port: 8085
spring:

  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.1.136:3306/myproject?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: 192.168.1.136
    port: 6379
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
  data:
    mongodb:
      uri: mongodb://192.168.1.111/project